{% set name = "netket" %}
{% set version = "2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/netket/netket/archive/v2.1.tar.gz
  sha256: 041d2b058c5d2945bf0a4194ad2bf3c426ad9b6ce0dd323a81a7154bc6e45452

build:
  number: 0
  skip: true  # [win]
  features:
    - nomkl  # [nomkl]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv --install-option=--cmake-args='-DNETKET_USE_LAPACK=OFF -DCMAKE_BUILD_TYPE=Release -DNETKET_USE_OPENMP=ON -DNETKET_USE_BLAS=ON -DNETKET_USE_SLEEF=ON'"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake >=3.12
    - ninja
    - libcxx
    - llvm-openmp            # [osx]
  host:
    - pip
    - python =3.7
    - mpich
    - mkl-devel {{ mkl }}  # [not nomkl]
    - blas                 # [nomkl]
    - blis                 # [nomkl]
    - libopenblas          # [nomkl]
  run:
    - numpy >=1.16
    - python =3.7
    - scipy >=1.2.1
    - numba >=0.48
    - mpich
    - mpi4py
    - tqdm
    - mkl   # [not nomkl]
    - blis  # [nomkl]
    - libcxx
    - llvm-openmp # [osx]

test:
  imports:
    - netket

about:
  home: https://www.netket.org
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Machine Learning for Many-Body Quantum Systems'
  description: |
    NetKet is an open-source project delivering cutting-edge methods 
    for the study of many-body quantum systems with artificial neural 
    networks and machine learning techniques. It is a Python library 
    built on C++ primitives.
  doc_url: https://www.netket.org/documentation.html
  dev_url: https://github.com/netket/netket

extra:
  recipe-maintainers:
    - PhilipVinc
    - gcarleo
